version: '3'
services:
  server:
    image: nokamoto13/example-ping-service-server:v0
    ports:
      - 9000:9000
  linkerd:
    image: buoyantio/linkerd:1.5.0
    command: /config.yaml
    volumes:
      - ./linkerd.yaml:/config.yaml
    depends_on:
      - server
    ports:
      - 8080:8080
      - 9990:9990
  prom:
    image: prom/prometheus:v2.4.3
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - linkerd
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:5.3.1
    volumes:
      - ./datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml:ro
      - ./dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml:ro
      - ./linkerd-viz.json:/var/lib/grafana/dashboards/linkerd-viz.json:ro
    depends_on:
      - prom
    ports:
      - 3000:3000
